[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Raphael Sahann <raphael.sahann@univie.ac.at>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
